#!/usr/bin/env bash
# Generates the standalone Cloudflare deploy config from environment variables.
#
# Account, database and worker identifiers are deliberately NOT committed:
# wrangler performs no variable interpolation inside its config file, so the
# file is generated at deploy time and git-ignored instead.
#
# Workers observability is deliberately OFF. Shared pages authenticate with a
# bearer token in the URL path (/share/<token>), and Cloudflare's invocation
# logs record the full request URL — which would put live bearer credentials
# into account-visible, retained Workers Logs. Redacting inside the Worker
# cannot help: the platform captures the URL before user code runs. Disabling
# observability is the only fix available without changing the share URL
# format, and security outranks invocation logs for this Worker.
#
# Do not flip this back on while share tokens live in the URL path. If
# observability is needed later, move the token out of the path first
# (session exchange) — see docs/SHARED_PAGES.md.
#
# Required: CLOUDFLARE_D1_DATABASE_NAME, CLOUDFLARE_D1_DATABASE_ID
# Optional: CLOUDFLARE_WORKER_NAME (default bitrix-deal-dashboard)
#           CLOUDFLARE_COMPATIBILITY_DATE (default 2026-05-15)
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$project_root"

: "${CLOUDFLARE_D1_DATABASE_NAME:?set CLOUDFLARE_D1_DATABASE_NAME (e.g. ibox-dashboard-staging)}"
: "${CLOUDFLARE_D1_DATABASE_ID:?set CLOUDFLARE_D1_DATABASE_ID (uuid from: wrangler d1 create <name>)}"
worker_name="${CLOUDFLARE_WORKER_NAME:-bitrix-deal-dashboard}"
compat_date="${CLOUDFLARE_COMPATIBILITY_DATE:-2026-05-15}"
out="${project_root}/wrangler.generated.jsonc"

cat > "$out" <<JSON
{
  // GENERATED by scripts/cf-config.sh — do not edit, do not commit.
  "\$schema": "node_modules/wrangler/config-schema.json",
  "name": "${worker_name}",
  "main": "./dist/server/index.js",
  "compatibility_date": "${compat_date}",
  "compatibility_flags": ["nodejs_compat"],
  "assets": { "directory": "./dist/client" },
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "${CLOUDFLARE_D1_DATABASE_NAME}",
      "database_id": "${CLOUDFLARE_D1_DATABASE_ID}"
    }
  ],
  // Server-side background refresh. The cadence is fixed here; the runtime
  // on/off switch is app_settings.autoSyncMinutes, which scheduled() reads.
  "triggers": { "crons": ["*/15 * * * *"] },
  "observability": { "enabled": false }
}
JSON

echo "Generated ${out} for worker '${worker_name}' (D1: ${CLOUDFLARE_D1_DATABASE_NAME})."
