#!/usr/bin/env bash
set -euo pipefail

# Consume the prompt exactly like the real noninteractive CLIs.
prompt="$(cat)"
: "${prompt:=empty}"

plan='{"summary":"Two independent fixture documents with cross-agent review.","unresolvedDecisions":[],"tasks":[{"id":"codex-doc","title":"Add Codex fixture","agent":"codex","objective":"Create the Codex fixture document.","dependsOn":[],"ownedPaths":["docs/codex-fixture.md"],"acceptanceCriteria":["Document exists"],"testCommands":[]},{"id":"claude-doc","title":"Add Claude fixture","agent":"claude","objective":"Create the Claude fixture document.","dependsOn":[],"ownedPaths":["docs/claude-fixture.md"],"acceptanceCriteria":["Document exists"],"testCommands":[]}]}'

case "${AI_TEAM_PHASE:-}" in
  plan|plan_revise) result="$plan" ;;
  plan_review) result='{"approved":true,"feedback":[],"unresolvedDecisions":[]}' ;;
  implement)
    if [[ "${AI_TEAM_AGENT:-}" == "codex" ]]; then
      file="docs/codex-fixture.md"
    else
      file="docs/claude-fixture.md"
    fi
    mkdir -p docs
    printf '# %s fixture\n\nGenerated by the mock executable.\n' "${AI_TEAM_AGENT:-unknown}" > "$file"
    result="{\"summary\":\"Created ${file}\",\"testsRun\":[],\"risks\":[]}"
    ;;
  review) result='{"approved":true,"findings":[],"notes":["Fixture approved"]}' ;;
  revise) result='{"summary":"Applied mock revision","testsRun":[],"risks":[]}' ;;
  *) printf 'Unexpected mock phase: %s\n' "${AI_TEAM_PHASE:-unset}" >&2; exit 2 ;;
esac

if [[ "${AI_TEAM_AGENT:-}" == "codex" ]]; then
  output=""
  while [[ "$#" -gt 0 ]]; do
    if [[ "$1" == "--output-last-message" ]]; then output="$2"; break; fi
    shift
  done
  [[ -n "$output" ]]
  printf '%s' "$result" > "$output"
else
  printf '{"type":"result","structured_output":%s}' "$result"
fi
